[package]
name = "chess_twitter_bot"
version = "0.1.0"
authors = ["Lancelot OWCZARCZAK <lowczarc@student.42.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
chess = "3.0.1"
rust_twitter_bot_lib = { git = "https://github.com/lowczarc/rust_twitter_bot_lib" }
image = "0.21.1"
toml = "0.5.0"
