[package]
name = "chess_twitter_bot"
version = "0.1.0"
authors = ["Lancelot OWCZARCZAK <lowczarc@student.42.fr>"]
edition = "2018"

[dependencies]
chess = "3.0.1"
rust_twitter_bot_lib = { git = "https://github.com/lowczarc/rust_twitter_bot_lib" }
